# Generated by Django 3.1.2 on 2020-12-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_auto_20201214_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockpunch',
            name='clock',
            field=models.BooleanField(),
        ),
    ]
