# Generated by Django 3.1.2 on 2020-12-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_auto_20201214_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockpunch',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
