# Generated by Django 3.1.2 on 2020-12-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_auto_20201215_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockpunch',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
