# Generated by Django 3.1.2 on 2020-12-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_auto_20201217_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockpunch',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
