# Generated by Django 3.1.2 on 2021-01-14 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_auto_20201222_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clockpunch',
            options={'ordering': ['-date_time'], 'verbose_name_plural': 'clockpunches'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-day']},
        ),
    ]
