# Generated by Django 3.1.2 on 2021-01-31 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0012_auto_20210131_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheets.week'),
        ),
    ]
